export const ACTION_TYPES= {
    ADD_NEWS_REQUEST: "ADD_NEWS_REQUEST",
    ADD_NEWS_SUCCESS: "ADD_NEWS_SUCCESS",
    ADD_NEWS_ERROR: "ADD_NEWS_ERROR",
    GET_NEWS_REQUEST:"GET_NEWS_REQUEST",
    GET_NEWS_SUCCESS:"GET_NEWS_SUCCESS",
    GET_NEWS_ERROR:"GET_NEWS_ERROR",
}